// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaidumggjmkttfzvogov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhaWR1bWdnam1rdHRmenZvZ292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTYxNDcsImV4cCI6MjA2MjM3MjE0N30.I5P6Z-4SfN8dxwLRCTxZSz-6v041OD4oWoIkHsXh_9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);